export const driverConstants = {
    CREATE_DRIVER_REQUEST: 'CREATE_DRIVER_REQUEST',
    CREATE_DRIVER_FALIURE: 'CREATE_DRIVER_FALIURE',
    CREATE_DRIVER_SUCCESS: 'CREATE_DRIVER_SUCCESS',
    GETALL_DRIVERS_REQUEST: 'GETALL_DRIVERS_REQUEST',
    GETALL_DRIVERS_FALIURE: 'GETALL_DRIVERS_FALIURE',
    GETALL_DRIVERS_SUCCESS: 'GETALL_DRIVERS_SUCCESS',
    DELETE_DRIVER_REQUEST: 'DELETE_DRIVER_REQUEST',
    DELETE_DRIVER_FALIURE: 'DELETE_DRIVER_FALIURE',
    DELETE_DRIVER_SUCCESS: 'DELETE_DRIVER_SUCCESS',
    UPDATES_DRIVER_REQUEST: 'UPDATES_DRIVER_REQUEST',
    UPDATES_DRIVER_FALIURE: 'UPDATES_DRIVER_FALIURE',
    UPDATES_DRIVER_SUCCESS: 'UPDATES_DRIVER_SUCCESS'
};
export const bikeConstants = {
    CREATE_BIKE_REQUEST: 'CREATE_BIKE_REQUEST',
    CREATE_BIKE_FALIURE: 'CREATE_BIKE_FALIURE',
    CREATE_BIKE_SUCCESS: 'CREATE_BIKE_SUCCESS',
    GETALL_BIKE_REQUEST: 'GETALL_BIKE_REQUEST',
    GETALL_BIKE_FALIURE: 'GETALL_BIKE_FALIURE',
    GETALL_BIKE_SUCCESS: 'GETALL_BIKE_SUCCESS',
    GET_AVAILABLE_BIKE_REQUEST: 'GET_AVAILABLE_BIKE_REQUEST',
    GET_AVAILABLE_BIKE_FALIURE: 'GET_AVAILABLE_BIKE_FALIURE',
    GET_AVAILABLE_BIKE_SUCCESS: 'GET_AVAILABLE_BIKE_SUCCESS',
    DELETE_BIKE_REQUEST: 'DELETE_BIKE_REQUEST',
    DELETE_BIKE_FALIURE: 'DELETE_BIKE_FALIURE',
    DELETE_BIKE_SUCCESS: 'DELETE_BIKE_SUCCESS',
    UPDATES_BIKE_REQUEST: 'UPDATES_BIKE_REQUEST',
    UPDATES_BIKE_FALIURE: 'UPDATES_BIKE_FALIURE',
    UPDATES_BIKE_SUCCESS: 'UPDATES_BIKE_SUCCESS'
};
export const inqConstants = {

    GETALL_INQ_REQUEST: 'GETALL_INQ_REQUEST',
    GETALL_INQ_FALIURE: 'GETALL_INQ_FALIURE',
    GETALL_INQ_SUCCESS: 'GETALL_INQ_SUCCESS',
    GETONE_INQ_REQUEST: 'GETONE_INQ_REQUEST',
    GETONE_INQ_FALIURE: 'GETONE_INQ_FALIURE',
    GETONE_INQ_SUCCESS: 'GETONE_INQ_SUCCESS',
    DELETE_INQ_REQUEST: 'DELETE_INQ_REQUEST',
    DELETE_INQ_FALIURE: 'DELETE_INQ_FALIURE',
    DELETE_INQ_SUCCESS: 'DELETE_INQ_SUCCESS',
    RESOLVE_INQ_REQUEST: 'RESOLVE_INQ_REQUEST',
    RESOLVE_INQ_FALIURE: 'RESOLVE_INQ_FALIURE',
    RESOLVE_INQ_SUCCESS: 'RESOLVE_INQ_SUCCESS',
};
export const msgConstants = {

    CREATE_MSG_REQUEST: 'CREATE_MSG_REQUEST',
    CREATE_MSG_FALIURE: 'CREATE_MSG_FALIURE',
    CREATE_MSG_SUCCESS: 'CREATE_MSG_SUCCESS',
    DELETE_MSG_REQUEST: 'DELETE_MSG_REQUEST',
    DELETE_MSG_FALIURE: 'DELETE_MSG_FALIURE',
    DELETE_MSG_SUCCESS: 'DELETE_MSG_SUCCESS',
    UPDATE_MSG_REQUEST: 'UPDATE_MSG_REQUEST',
    UPDATE_MSG_FALIURE: 'UPDATE_MSG_FALIURE',
    UPDATE_MSG_SUCCESS: 'UPDATE_MSG_SUCCESS',
    FETCH_MSG_REQUEST: 'FETCH_MSG_REQUEST',
    FETCH_MSG_FALIURE: 'FETCH_MSG_FALIURE',
    FETCH_MSG_SUCCESS: 'FETCH_MSG_SUCCESS',
};